# Generated by Django 3.2.5 on 2021-07-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Title', max_length=50)),
                ('rating', models.CharField(default='No Rating', max_length=50)),
            ],
        ),
    ]
