# Generated by Django 3.2.5 on 2021-08-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0003_alter_movies_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='director',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='movies',
            name='leadingActor',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='movies',
            name='movieInfo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='movies',
            name='runTime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
