# Generated by Django 3.2.5 on 2021-08-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0004_auto_20210802_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='runTime',
            field=models.CharField(default='2h 30m', max_length=20),
        ),
    ]
